# Common configurations for aap and nf
mysql: &MYSQL
  dsn: "root:123456@tcp(mysql:3306)/engineerpro?charset=utf8mb4&parseTime=True&loc=Local"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis: &REDIS
  addr: redis:6379

# Configuration for aap service connection
authenticate_and_post_config: &AAP
  port: 19001
  mysql: *MYSQL
  redis: *REDIS

# Configuration for nf service connection
newsfeed_config: &NF
  port: 19002
  mysql: *MYSQL
  redis: *REDIS

# Configurations for web app
web_config:
  # Connection configs
  port: 19003
  api_version: ["v1"]
  authenticate_and_post:
    hosts: ["aap:19001"]
  newsfeed:
    hosts: ["newsfeed:19002"]
  redis: *REDIS