# Common configurations for aap and nf
mysql: &MYSQL
  dsn: "root:123456@tcp(mysql:3306)/engineerpro?charset=utf8mb4&parseTime=True&loc=Local"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis: &REDIS
  addr: "redis:6379"
kafka: &KAFKA
  topic: "engineerpro"
  brokers: ["kafka:9092"]
logger: &LOGGER
  level: "debug" # info, warning, error, dpanic, panic, error

# Configuration for aap service connection
authenticate_and_post_config: &AAP
  port: 19001
  logger: *LOGGER
  mysql: *MYSQL
  redis: *REDIS
  newsfeed_publishing:
    hosts: ["nfp:19004"]

# Configuration for nf service connection
newsfeed_config: &NF
  port: 19002
  logger: *LOGGER
  mysql: *MYSQL
  redis: *REDIS
  kafka: *KAFKA

# Configuration for nfp service
newsfeed_publishing_config: &NFP
  port: 19004
  logger: *LOGGER
  redis: *REDIS
  kafka: *KAFKA
  authenticate_and_post:
    hosts: ["aap:19001"]

# Configurations for web app
web_config:
  port: 19003
  logger: *LOGGER
  api_version: ["v1"]
  authenticate_and_post:
    hosts: ["aap:19001"]
  newsfeed:
    hosts: ["nf:19002"]
  redis: *REDIS
