# Common configurations for aap and nf
mysql: &MYSQL
  dsn: "quangmx:2511@tcp(192.168.0.103:3306)/social-network?charset=utf8mb4&parseTime=True&loc=Local"
  defaultStringSize: 256
  disableDatetimePrecision: true
  dontSupportRenameIndex: true
  skipInitializeWithVersion: false
redis: &REDIS
  addr: "192.168.0.103:6379"
  password: "2511"

# Configuration for aap service connection
authenticate_and_post_config: &AAP
  port: 19001
  mysql: *MYSQL
  redis: *REDIS

# Configuration for nf service connection
newsfeed_config: &NF
  port: 19002
  mysql: *MYSQL
  redis: *REDIS

# Configurations for web app
web_config:
  # Connection configs
  port: 19003
  api_version: ["v1"]
  authenticate_and_post:
    hosts: ["192.168.0.103:19001"]
  newsfeed:
    hosts: ["192.168.0.103:19002"]
  redis: *REDIS