version: '3'
services:

  web:
    build:
      context: .
      dockerfile: cmd/web_app/Dockerfile
      target: test_env
    image: webapp
    depends_on:
      - newsfeed
      - aap
    networks:
      - intranet
      - default
    hostname: web
    ports:
      - 19003:19003

  aap:
    build:
      context: .
      dockerfile: cmd/authen_and_post_svc/Dockerfile
      target: test_env
    image: aapsvc
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - intranet
    hostname: aap
    ports:
      - 19001:19001

  newsfeed:
    build:
      context: .
      dockerfile: cmd/newsfeed_svc/Dockerfile
      target: test_env
    image: nfsvc
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - intranet
    hostname: nf
    ports:
      - 19002:19002

  nfp:
    build:
      context: .
      dockerfile: cmd/newsfeed_publishing_svc/Dockerfile
      target: test_env
    image: nfpsvc
    depends_on:
      - aap
      - kafka
    networks:
      - intranet
    hostname: nfp
    ports:
      - 19004:19004
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - intranet
    hostname: kafka
    ports:
      - 9092:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - intranet
    hostname: zookeeper
    ports:
      - 2181:2181

  mysql:
    image: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf  # Global default settings
      - ./data/mysql:/var/lib/mysql  # Data of databases
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: engineerpro
    networks:
      - intranet
    hostname: mysql
    ports:
      - 3306:3306
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    networks:
      - intranet
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  intranet: {}
  default: {}
