version: "3"
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - intranet
    hostname: kafka
    ports:
      - 9092:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - intranet
    hostname: zookeeper
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD", "zookeeper-shell", "zookeeper:2181", "ls", "/"]
      timeout: 1s
      retries: 3

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: engineerpro
    networks:
      - intranet
    hostname: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 3

  redis:
    image: redis:7.2.4
    networks:
      - intranet
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 1s
      retries: 3

networks:
  intranet: {}
  default: {}
