definitions:
  types.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  types.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: A simple social network management service API in Go using Gin framework
  title: Gin Social Network Service
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: check username and password
      parameters:
      - description: login param
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.MessageResponse'
swagger: "2.0"
